version: '3.7'
services:
  agoldsmith-ssh:
    build:
      context: './ssh-server/'
      dockerfile: 'Dockerfile'
    volumes:
      - ./ssh-server/node-app:/home/node/app:delegated
    ports:
      - '8080:80'
      - '2222:2222'
    environment:
      - NODE_ENV=development
    command: /entrypoint-dev.sh